const TOGGLE_MEMORIZED = 'TOGGLE_MEMORIZED';
const REMOVE = 'REMOVE';
const ADD_WORD = 'ADD_WORD';
const TOGGLE_FORM = 'TOGGLE_FORM';
const SET_FILTER_MODE = 'SET_FILTER_MODE';
const FETCH_DATA_WORD = 'FETCH_DATA_WORD';

export const actionType = {
  TOGGLE_MEMORIZED,
  REMOVE,
  ADD_WORD,
  TOGGLE_FORM,
  SET_FILTER_MODE,
  FETCH_DATA_WORD,
};
